- src/codegen/compiler.cc
- src/runtime/runtime-compiler.cc
https://linear.app/replay/issue/RUN-513
> Allow recorded events during deterministic compilations

- src/api/api.cc
- src/runtime/runtime-debug.cc
This fixes a couple problems from #39 -- we're incrementing the progress counter twice in Runtime_RecordReplayAssertExecutionProgress, and need to call the RecordReplayEnableProgressCheckpoints API in order to allow creating checkpoints at arbitrary progress values.
> Fix a couple progress counter issues

- src/codegen/compiler.cc
- src/runtime/runtime-debug.cc
We're seeing some crashes while replaying from https://github.com/replayio/chromium-v8/pull/47 where instrumentation sites are accessed on the main thread that are out of range, presumably indicating that they weren't copied over to the main thread vector from the full vector before the script starts executing.  It's not clear why this is happening but this PR should fix the problem, by simplifying how we deal with these two vectors and copying instrumentation sites to the main thread vector as needed.
> Copy instrumentation sites from full vector as needed

- src/codegen/compiler.cc
https://linear.app/replay/issue/GTM-455
> Don't emit record/replay opcodes in eval'ed scripts on worker threads

- src/api/api.cc
This fixes a warning I saw in some logs after an exception was thrown in the replaying-only script (the exception is expected, it is related to sourcemap URL processing).
> Watch out for exceptions being thrown while events are disallowed

- include/js_protocol.pdl
- src/api/api.cc
- src/builtins/x64/builtins-x64.cc
- src/compiler/js-inlining.cc
- src/debug/debug.cc
- src/inspector/injected-script.cc
- src/interpreter/bytecode-array-builder.cc
- src/runtime/runtime-debug.cc
- src/runtime/runtime.h
For https://linear.app/replay/issue/RUN-787
> Keep track of persistent object IDs for objects created with 'new'

- src/base/build_config.h
* Disable `V8_HAS_PKU_JIT_WRITE_PROTECT` to workaround `dlsym` being unable to lookup `pkey_*` functions.
* https://linear.app/replay/issue/RUN-1085/chromium-108-crash-getkeypermission-dlsym-failed
> RUN-1085: disable `V8_HAS_PKU_JIT_WRITE_PROTECT`

- src/api/api.cc
* added `RECORD_REPLAY_TEST_ENVIRONMENT` to api.cc and use it to enable "all experimental flags"
* also fix flags to use `set` for lookup, instead of `vector`
* https://linear.app/replay/issue/RUN-1341/chromium-v8-enable-events-and-in-the-future-any-experimental-flags-if
* Part of: https://linear.app/replay/issue/RUN-1327/enable-experimental-flags-in-test-suites-by-default
> RUN-1341: RECORD_REPLAY_TEST_ENVIRONMENT

- src/api/api.cc
Re-enable experimental flag, after merging replayio/chromium#421.
* https://linear.app/replay/issue/RUN-1392/fix-events-recorder-crashes
> RUN-1341: re-enable events experimental flag (part of RUN-1392)

- include/js_protocol.pdl
- include/v8-container.h
- include/v8-object.h
- src/api/api.cc
- src/debug/debug-interface.cc
- src/debug/debug-interface.h
- src/debug/debug-property-iterator.cc
- src/debug/debug-property-iterator.h
- src/inspector/injected-script.cc
- src/inspector/injected-script.h
- src/inspector/v8-debugger.cc
- src/inspector/v8-debugger.h
- src/inspector/v8-runtime-agent-impl.cc
- src/inspector/v8-runtime-agent-impl.h
- src/inspector/value-mirror.cc
- src/inspector/value-mirror.h
- src/objects/elements-inl.h
- src/objects/elements.cc
- src/objects/elements.h
- src/objects/hash-table-inl.h
- src/objects/hash-table.h
- src/objects/keys.cc
- src/objects/keys.h
- src/objects/map-inl.h
- src/objects/map.h
- src/objects/ordered-hash-table.h
- src/objects/swiss-name-dictionary-inl.h
- src/objects/swiss-name-dictionary.h
Reverts replayio/chromium-v8#103.
* Caused command crashes.
* Discussed [here](https://linear.app/replay/issue/RUN-1315#comment-26f96699).
* Will fix, and test with an eye on command crashes before sending it back in.
> Revert "RUN-1429: adding `KeyIterationParams` to v8 prop (key + element) iteration"

- src/inspector/value-mirror.cc
* Warning: This is currently the released V8 HEAD.
* I rolled these back accidentally as part of the `RUN-1315` commit that caused more command crashes. But this change actually prevents crashes. Bringing it back in.
* Discussed [here](https://discord.com/channels/779097926135054346/798654183115980840/threads/1084143544450687095).
* Tests passed:
* [livetests](https://github.com/replayio/build-test-dashboard/blob/master/270993b0-7294-47c1-8947-657e2027cc1f): 28 vs 2
* [playwright tests](https://github.com/replayio/build-test-dashboard/blob/master/4a559703-0128-4fda-89ce-8227d4b3f878) seem to be buggy 🤷‍♀️
> RUN-1478: stop trying to access unsanctioned getters

- src/api/api.cc
- src/execution/execution.cc
* https://linear.app/replay/issue/RUN-1488#comment-7786dc3a
* Test [here](https://github.com/replayio/build-test-dashboard/blob/master/2f9c2f2f-760c-47f3-9a50-48584af405bf): 45 vs. 5 ✔
* Only one command crash (as of now): https://ui.honeycomb.io/replay/datasets/backend/result/ES2oECKSscH
> RUN-1495: Assert Invoke

- src/api/api.cc
* enable events in test suites again, as a follow up of https://github.com/replayio/chromium/pull/439
> re-enable events

- src/api/api.cc
* Paired w/ https://github.com/replayio/chromium/pull/489
* https://linear.app/replay/issue/RUN-1609/flip-the-switch-in-the-chromium-runtime-to-enable-events-everywhere-%F0%9F%98%B2
> RUN-1609: enable events by default in the chromium runtime (v8)

- src/execution/microtask-queue.h
Paired w/ https://github.com/replayio/chromium/pull/490
* I removed this `Assert` [here](https://github.com/replayio/chromium-v8/pull/117/files).
* But it ended up being very useful!
* https://linear.app/replay/issue/RUN-1593/divergence-in-performmicrotaskcheckpoint
> Add back `MicrotaskQueue::PerformCheckpoint` Assert

- src/inspector/value-mirror.cc
* Paired w/ https://github.com/replayio/chromium/pull/495
* → https://linear.app/replay/issue/RUN-1592/fix-issues-related-to-events-and-event-previews
* Follow up will be needed to eliminate the whitelist: https://linear.app/replay/issue/RUN-1592#comment-4bc00037
* Link to follow-up: https://linear.app/replay/issue/RUN-1616/eliminate-native-getter-whitelist-in
> RUN-1592: add more native getters to whitelist manually

- src/api/api.cc
Paired w/ https://github.com/replayio/chromium/pull/519
* https://linear.app/replay/issue/RUN-1335/mismatch-in-singlethreadidletaskrunnerruntask#comment-6a4cbb7b
> RUN-1335: add `clear-idle-callbacks` feature flag

- include/v8.h
- src/api/api.cc
For RUN-1796 (https://linear.app/replay/issue/RUN-1796/add-recordreplayhadmismatch-api-to-linkerdriver)
> Add RecordReplayHadMismatch API.

- include/js_protocol.pdl
- src/inspector/v8-debugger-agent-impl.cc
https://linear.app/replay/issue/RUN-1799
> Add execution context ID to CDP call frames

- src/api/api.cc
- src/debug/debug.cc
* paired w/ https://github.com/replayio/chromium/pull/647
* https://linear.app/replay/issue/RUN-1908/devtools-crashes-collect-garbage-button
> RUN-1908: Don't crash when opening CDT

- src/debug/debug-stack-trace-iterator.cc
- src/execution/frames.cc
* paired w/ https://github.com/replayio/chromium/pull/649
* https://linear.app/replay/issue/RUN-1920#comment-192befe2
> RUN-1920: Workaround for "Missing deoptimization information for OptimizedFrame::Summarize"

- include/js_protocol.pdl
- src/inspector/v8-debugger-agent-impl.cc
- src/inspector/v8-debugger-agent-impl.h
* paired w/ https://github.com/replayio/chromium/pull/663
* main fix: https://linear.app/replay/issue/RUN-1832#comment-95230d9f
* sneaky fix: optional `getPendingException` - https://linear.app/replay/issue/RUN-1190/fix-our-custom-v8-debuggergetpendingexception-to-mark-the-exception-as
* Tests passing ✔
> RUN-1832 + RUN-1190: Add `objectGroup` to `getPendingException` and make `exception` optional

- src/heap/cppgc/sweeper.cc
* paired w/ https://github.com/replayio/chromium/pull/670
* https://linear.app/replay/issue/RUN-1974/mismatch-in-sweepersweeperimplstart
> AutoDisallowEvents for `SweeperImpl::Start`

- src/base/logging.cc
- src/debug/debug.cc
* https://github.com/replayio/chromium/pull/676
* https://linear.app/replay/issue/RUN-2022/js-exceptions-are-not-reported-anymore-when-we-crash-in
> RUN-2022: Fix JS exception regression

- src/api/api.cc
- src/baseline/baseline-compiler.cc
- src/compiler/bytecode-graph-builder.cc
- src/debug/debug.cc
- src/objects/value-serializer.cc
- src/runtime/runtime-debug.cc
* https://linear.app/replay/issue/RUN-1988/detect-and-report-pc-mismatches-due-to-replay-command-handling
* Sneaky change:
* More `PerformSideEffectCheck` fixes (`RUN-1908`).
* Peg fixed `RUN-1618` to new `RUN-2037`
> RUN-1988: Detect and Report PC mismatches due to Replay command handling

- src/heap/cppgc/sweeper.cc
- src/heap/heap.cc
* paired w/ https://github.com/replayio/chromium/pull/736
* https://linear.app/replay/issue/RUN-2178#comment-425628a4
> RUN-2178: Disallow events in Heap::StartTearDown

- src/api/api.cc
- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/768
* https://linear.app/replay/issue/RUN-2232#comment-0fcda91b
> RUN-2232: Make OnProgressReached a no-op when events disallowed

- src/heap/concurrent-allocator.cc
- src/heap/large-spaces.cc
For https://linear.app/replay/issue/RUN-851
> Add diagnostics for heap allocation failures on background threads

- src/heap/heap.cc
https://linear.app/replay/issue/RUN-851
> Avoid GC when allocating on background threads while replaying

- src/debug/debug.cc
* paired w/ https://github.com/replayio/chromium/pull/841
* https://linear.app/replay/issue/RUN-2394#comment-001e925e
> RUN-2394: Add a way to query bytecode of a function

- src/execution/futex-emulation.cc
- src/execution/futex-emulation.h
For #RUN-2433 (https://linear.app/replay/issue/RUN-2433/order-global-mutex-in-futexemulation-code)
Parent issue #RUN-2378.
> Order global mutex in FutexEmulation.

- src/interpreter/bytecode-generator.cc
* paired w/ https://github.com/replayio/chromium/pull/889
* https://linear.app/replay/issue/RUN-2406#comment-44cd075b
> RUN-2406: Add breakpoints to ternary sub-expressions

- include/v8.h
- src/api/api.cc
For #RUN-2557 (https://linear.app/replay/issue/RUN-2557)
See prerequisite backend PR: https://github.com/replayio/backend/pull/8588
> Add `ReadSystemFileContents` API from linker.

- src/interpreter/bytecode-array-builder.cc
- src/interpreter/bytecode-array-builder.h
- src/interpreter/bytecode-generator.cc
- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/903
* https://linear.app/replay/issue/RUN-2341/breakpoint-in-nested-expressions-missing#comment-3cc4cc02
> RUN-2341: Break on all call expressions + prevent duplicates

- src/debug/debug.cc
Let's move the crashing behaviour over to the Linker, which can emit more error information before it finally self-destructs.
> Stop crashing V8 when encountering a bad command.

- src/api/api.cc
(This exposes this function for binding in windows Chromium.  Needed by  https://github.com/replayio/chromium/pull/913 .)
> Change signature of V8RecordReplayFinishRecording to DLLEXPORT

- src/ast/scopes.cc
This makes all outer bindings visible within inner scopes, regardless if they're referenced.  Behind a flag to check perf/memory effects.
> RUN-2604: Keep all bindings available in inner scopes when replaying

- include/v8.h
- src/api/api.cc
- src/execution/isolate.cc
* paired w/ https://github.com/replayio/chromium/pull/918
* This is to allow better traceable early-outs, which we want to use in #918 and others.
* Sneaky: Also fix a bug with `FeatureEnabled` not passing all parameters through.
> add `why` to V8RecordReplayIsInReplayCode

- include/v8.h
- src/api/api.cc
- src/codegen/compiler.cc
* paired w/ https://github.com/replayio/chromium/pull/938
* https://linear.app/replay/issue/RUN-2739/crash-in-localframeisprovisional-during-eval#comment-eea02f21
> [RUN-2739] add V8RecordReplayCrash + fix SetRecordReplayIgnore checks

- include/v8.h
- src/api/api.cc
- src/codegen/compiler.cc
* This caused Windows CI recordings to just timeout indefinitely.
* → Revert replayio/chromium-v8#194
> Revert "[RUN-2739] add V8RecordReplayCrash + fix SetRecordReplayIgnore checks"

- src/debug/debug.cc
- src/inspector/injected-script.cc
- src/inspector/v8-inspector-session-impl.cc
- src/inspector/v8-runtime-agent-impl.cc
* paired w/ https://github.com/replayio/chromium/pull/948
* https://linear.app/replay/issue/RUN-2607/generate-persistent-ids-for-dom-nodes#comment-417536e3
> [RUN-2607] Also call gGetAPIObjectIdCallback when producing `persistentId` in CDP bindRemoteObject logic

- include/v8.h
- src/api/api.cc
- src/codegen/compiler.cc
* paired w/ https://github.com/replayio/chromium/pull/949
* NOTE: This is just https://github.com/replayio/chromium-v8/pull/194/files but with a missing `DLLEXPORT` added.
* https://linear.app/replay/issue/RUN-2739/crash-in-localframeisprovisional-during-eval#comment-24d2f767
* https://linear.app/replay/issue/RUN-2795/run-ci-windows-recorder-crashes-are-not-detected
> [RUN-2739 + RUN-2794] Fix RUN-2739 changes

- include/v8.h
- src/api/api.cc
- src/execution/futex-emulation.cc
* paired w/ https://github.com/replayio/chromium/pull/962
* https://linear.app/replay/issue/RUN-2378/mismatch-in-futexemulationwaitsync#comment-912cbba5
> [RUN-2378] Disallow events in FutexEmulation, but order Wait calls

- src/api/api.cc
- src/debug/debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1052
* https://linear.app/replay/issue/RUN-2965/-record-replay-and-other-replay-only-props-are-not-available-after#comment-0070ead6
> Allow overriding some Replay globals

- src/interpreter/bytecode-generator.cc
- src/interpreter/bytecode-generator.h
* paired w/ https://github.com/replayio/chromium/pull/1137
* https://linear.app/replay/issue/RUN-3317/fix-sourcemapping-of-breakpoints-on-tokens-before-nested-expressions#comment-d1993788
> [RUN-3317] Move breakpoints into nested expressions

- src/inspector/injected-script.cc
- src/inspector/value-mirror.cc
- src/objects/keys.cc
My hope is this won't result in much of a perf hit.  It seems (using the benchmark mode in https://github.com/replayio/backend/pull/9634) that it increases object preview durations by a constant factor, and things are still largely in the same ballpark as master.
Keep track of the passed-in params in the PropertyAccumulator, and in the case of `canOverflow` or `full` pass a MUCH larger params page size (currently 100k) down to the rest of the v8 machinery.  That way we're very likely to get enough keys for a given object that when we sort them we'll end up with the keys we expect.  This is coupled with early out'ing from the loop where we create PropertyMirrors, so the result sent back to the command JS is always min(num-properties, requested-size).
I did also find one spot where the key …
> [RUN-3149] send large KeyIterationParams while iterating to accumulate keys, and shrink the PropertyMirrors array after

- src/inspector/v8-runtime-agent-impl.cc
- src/inspector/v8-runtime-agent-impl.h
* paired w/ https://github.com/replayio/chromium/pull/1149
* https://linear.app/replay/issue/RUN-3380/detached-replay-and-record-time-command-handling-are-incompatible#comment-b75b2fce
> [RUN-3380] Fix V8RuntimeAgentImpl::m_replayOnly

- src/debug/debug.cc
- src/execution/isolate.cc
https://linear.app/replay/issue/RUN-3391/mismatch-w-getorcreatepromisedependencygraphdata
> Call promise hook while recording when asserting on tracked object IDs

- src/api/api.cc
- src/debug/debug.cc
- src/interpreter/bytecode-array-builder.cc
- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1163
* https://linear.app/replay/issue/TT-4/fix-gethitcounts-replace-breakpoint-offsets-with-more-consistent-ids#comment-a7bbd0f6
> [TT-4] Use breakpoint `function_index` instead of `offset`

- src/heap/heap.cc
* paired w/ https://github.com/replayio/chromium/pull/1167
* https://linear.app/replay/issue/TT-743/mismatch-in-heapcollectgarbageonmemorypressure#comment-6aa5a5b5
> [TT-743] Disallow events in Heap::CollectGarbageOnMemoryPressure

- src/api/api.cc
* paired w/ https://github.com/replayio/chromium/pull/1176
* https://linear.app/replay/issue/TT-211/mark-iframesextensionsdevtools-recordings-with-different-metadata
> Expose V8RecordReplayAddMetadata

- src/execution/isolate.cc
* paired w/ https://github.com/replayio/chromium/pull/1183
* https://linear.app/replay/issue/TT-844/many-runtime-promise-hook-warnings-when-asserting-on-tracked-objects#comment-623d803f
> Remove Assert warnings due to promise hooks

- src/api/api.cc
- src/compiler/js-call-reducer.cc
- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1189
* https://linear.app/replay/issue/TT-187/[superblocks]-mismatch-involving-promisereject#comment-663e6944
> Assert JSPromise::set_has_handler

- src/api/api.cc
- src/base/replayio.h
- src/compiler/js-call-reducer.cc
- src/inspector/v8-runtime-agent-impl.cc
- src/objects/objects.cc
- src/runtime/runtime-debug.cc
- src/runtime/runtime-promise.cc
* paired w/ https://github.com/replayio/chromium/pull/1193
* SLN: https://linear.app/replay/issue/TT-187/[superblocks]-mismatch-involving-promisereject#comment-191d5fc4
* Improved Asserts: https://linear.app/replay/issue/TT-187/[superblocks]-mismatch-involving-promisereject#comment-2ef701e6
> [TT-187] Don't report in `JSPromise::Reject` if recording did not have a handler

- src/debug/debug.cc
Mini update without a Linear issue:
* paired w/ https://github.com/replayio/chromium/pull/1222
* I saw this generate a ton of unnecessary noise when debugging the `Date.now` divergence recently.
* -> Let's mute these if events are disallowed.
> Stop object JS Assert warnings

- src/api/api.cc
* paired w/ https://github.com/replayio/chromium/pull/1220
* https://linear.app/replay/issue/TT-1116/fix-chrome-extension-popup-recordings-metadata#comment-288f26db
> Fix uri for Extension popup recordings

- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1231
* https://linear.app/replay/issue/TT-1177/js-asserts-cannot-create-a-handle-without-a-handlescope#comment-9b70b9b6
> [TT-1177] Add `HandleScope` to `GetScriptLocationString`

- src/api/api.cc
https://linear.app/replay/issue/TT-1313/enable-dependency-graph-by-default
> Enable dependency graph by default

- src/objects/value-serializer.cc
Disable switching serialization formats based on storage representations for JS objects and arrays.
counterpart to https://github.com/replayio/chromium/pull/1251
> [TT-492] force slowpath in value serializer

- src/api/api.cc
- src/debug/debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1267
* https://linear.app/replay/issue/TT-1390/fix-exception-reporting-for-our-own-sourcemap-scripts
> [TT-1390] Fix exception reporting for our own sourcemap scripts

- src/api/api.cc
- src/execution/messages.cc
* paired w/ https://github.com/replayio/chromium/pull/1268
* https://linear.app/replay/issue/TT-1396/fix-a-recorder-and-linker-crash-in-recordreplayonexceptionunwind#comment-f1881f1e
> [TT-1396] Prevent out-of-bounds access in `RecordReplayOnExceptionUnwind`

- src/api/api.cc
* paired w/
* https://github.com/replayio/backend/pull/10259
* https://github.com/replayio/chromium/pull/1266
* https://linear.app/replay/issue/TT-240/capture-mouse-and-keyboard-session-events-from-test-automation#comment-372ec267
> [TT-240] Add support for synthetic events

- src/api/api.cc
- src/debug/debug.cc
- src/objects/objects.cc
https://linear.app/replay/issue/TT-1361/%5Bsuperblocks-framercom-replit%5D-mismatch-in-jspromisereject
> Fix mismatches when dependency graph is enabled

- src/debug/debug.cc
- src/objects/objects.cc
* https://linear.app/replay/issue/PRO-901/add-nested-persistent-id-to-promisesettled-nodes
* paired w/
* https://github.com/replayio/chromium/pull/1311
> [PRO-901] Add DG `adoptedPromise` edge

- src/objects/objects.cc
* https://linear.app/replay/issue/PRO-901/add-nested-persistent-id-to-promisesettled-nodes
* Correction for https://github.com/replayio/chromium-v8/pull/264
* → Rejections cannot be delayed by promise adoption.
* paired w/
* https://github.com/replayio/chromium/pull/1311
> [PRO-901] Add DG `adoptedPromise` edge (remove from reject)

- src/execution/messages.cc
it helps to close https://linear.app/replay/issue/PRO-1150/analysis-fatal-errors-causing-many-chats-to-fail
extracted from https://github.com/replayio/chromium-v8/pull/271
pairs with https://github.com/replayio/chromium/pull/1323
> Replay error stacks

- src/api/api.cc
https://linear.app/replay/issue/PRO-1417/failing-assert-on-column-mismatch
pairs with https://github.com/replayio/chromium/pull/1331
> Remove column from `JS Function::Call` assert
