replayio/chromium-v8

- src/api/api.cc
- src/heap/concurrent-marking.cc
- src/heap/cppgc/concurrent-marker.cc
- src/heap/heap.cc
- src/heap/mark-compact.cc
- src/heap/memory-allocator.cc
- src/heap/scavenger.cc
- src/heap/sweeper.cc
- src/wasm/module-compiler.cc
- src/wasm/module-instantiate.cc
- src/wasm/wasm-serialization.cc
Diagnostics for https://github.com/RecordReplay/backend/issues/5661
> Add assertions for result of GetMaxConcurrency callbacks

- src/heap/cppgc/concurrent-marker.cc
- src/wasm/module-compiler.cc
Fix some build breaks from https://github.com/RecordReplay/chromium-v8/pull/7
> Fix some build breaks

- src/heap/heap.cc
For https://github.com/RecordReplay/backend/issues/5704
> Allow major GCs when recording/replaying

- src/api/api.cc
Corollary to https://github.com/RecordReplay/chromium/pull/37
> Fix build break

- src/api/api.cc
https://linear.app/replay/issue/RUN-426/use-recordreplayrememberrecording-in-chromium
> Use RecordReplayRememberRecording API

- src/debug/debug.cc
https://linear.app/replay/issue/RUN-445/character-encoding-of-scripts-in-chromiumnode
> Fix character encoding for sources

- src/api/api.cc
https://linear.app/replay/issue/RUN-489/add-diagnostics-in-v8objectclone
> Add diagnostics in v8::Object::Clone

- src/api/api.cc
https://linear.app/replay/issue/RUN-523/add-v8-api-for-setting-default-recordreplay-context
> Add API for setting default record/replay context

- src/builtins/builtins-global.cc
V8 counterpart to https://github.com/replayio/chromium/pull/90
> Add comments associating recording assertions with issues

- include/js_protocol.pdl
- src/ast/ast-value-factory.cc
- src/debug/debug-scopes.cc
- src/debug/debug-scopes.h
- src/debug/debug-stack-trace-iterator.cc
- src/debug/debug.cc
- src/inspector/v8-debugger-agent-impl.cc
- src/inspector/v8-debugger-agent-impl.h
- src/interpreter/bytecode-generator.cc
- src/parsing/parse-info.cc
- src/runtime/runtime-debug.cc
https://linear.app/replay/issue/RUN-567
> Fix some performance problems when gathering frames

- src/api/api.cc
- src/debug/debug.cc
https://linear.app/replay/issue/RUN-587
> Add diagnostic RECORD_REPLAY_DISABLE_FEATURES env var

- src/debug/debug.cc
https://linear.app/replay/issue/RUN-612
> Only ignore the special record/replay internal script

- src/api/api.cc
Interface between `inspector_networ_agent.cc` and `record_replay_interface.cc`.  Needs to land before that chromium code can land.
> Add callback junction for replay browser events

- src/api/api.cc
- src/execution/messages.cc
This is the prerequisite for network monitoring.
> Make more network-related driver functions available

- src/codegen/compiler.cc
https://linear.app/replay/issue/RUN-634
> Disable compiling 'use asm' scripts as wasm

- src/execution/stack-guard.cc
https://linear.app/replay/issue/RUN-651
> Don't handle interrupts while events are disallowed

- src/codegen/compiler.cc
- src/debug/debug-interface.cc
- src/heap/concurrent-marking.cc
- src/heap/cppgc/concurrent-marker.cc
- src/heap/mark-compact.cc
- src/heap/memory-allocator.cc
- src/heap/scavenger.cc
- src/heap/sweeper.cc
- src/inspector/injected-script.cc
- src/inspector/v8-runtime-agent-impl.cc
- src/wasm/module-compiler.cc
- src/wasm/module-instantiate.cc
- src/wasm/wasm-serialization.cc
- third_party/inspector_protocol/crdtp/dispatch.cc
As for https://github.com/replayio/chromium/pull/159
> Remove unused recording assertions

- include/v8.h
- src/api/api.cc
- src/codegen/compiler.cc
- src/debug/debug.cc
- src/execution/isolate.cc
- src/handles/global-handles.cc
- src/heap/gc-tracer.cc
- src/heap/heap.cc
- src/heap/item-parallel-job.cc
- src/heap/mark-compact.cc
- src/heap/memory-reducer.cc
- src/heap/scavenger.cc
- src/interpreter/bytecode-array-builder.cc
- src/interpreter/bytecode-generator.cc
- src/profiler/heap-snapshot-generator.cc
- src/runtime/runtime-compiler.cc
- src/wasm/wasm-code-manager.h
- src/wasm/wasm-engine.cc
For https://linear.app/replay/issue/GTM-442
> Associate more IsRecordingOrReplaying tests with features

- src/codegen/compiler.cc
- src/interpreter/bytecode-generator.cc
For https://linear.app/replay/issue/GTM-442
> Fix build break and check failure

- src/debug/debug.cc
- src/inspector/v8-console-message.cc
https://linear.app/replay/issue/RUN-695
> Ignore console messages added on worker threads

- src/api/api.cc
For https://linear.app/replay/issue/GTM-442
> Update disabled features

- src/api/api.cc
- src/codegen/compiler.cc
- src/interpreter/bytecode-array-builder.cc
- src/runtime/runtime-debug.cc
https://linear.app/replay/issue/RUN-701
This also has some cleanup/improvements to the disabled features code which I was using while testing.
> Support background compile tasks when recording/replaying

- src/execution/isolate.cc
Chromium replays are generating warnings because we now compile the record/replay script while events are disallowed, so as we work towards not being able to run this script at all when recording.  The IDs for scripts that are registered with the recorder need to be consistent between recording/replaying (or more precisely between different replays) so we should be drawing them from a separate pool when events are disallowed and ensure they will be consistent.
> Support creating scripts while events are disallowed

- include/v8.h
- src/api/api.cc
https://linear.app/replay/issue/RUN-707
> Specify name when registering pointers

- src/api/api.cc
https://linear.app/replay/issue/RUN-718
> Add V8IsMainThread export

- src/heap/local-heap.cc
https://linear.app/replay/issue/RUN-722
> Disallow events when waiting for a main thread GC on a background thread

- src/api/api.cc
- src/execution/isolate.cc
https://linear.app/replay/issue/RUN-727
> Separate disabling of Isolate::CountUsage into its own feature

- src/api/api.cc
- src/handles/global-handles.cc
- src/heap/item-parallel-job.cc
- src/heap/mark-compact.cc
- src/heap/memory-reducer.cc
- src/heap/scavenger.cc
- src/runtime/runtime-compiler.cc
- src/wasm/wasm-engine.cc
https://linear.app/replay/issue/RUN-728
> Remove deterministic-tasks feature

- src/baseline/baseline-assembler.h
- src/baseline/baseline-compiler.cc
- src/baseline/x64/baseline-assembler-x64-inl.h
- src/codegen/external-reference.cc
- src/codegen/external-reference.h
- src/compiler/bytecode-graph-builder.cc
- src/compiler/effect-control-linearizer.cc
- src/compiler/memory-optimizer.cc
- src/compiler/opcodes.h
- src/compiler/simplified-lowering.cc
- src/compiler/simplified-operator.cc
- src/compiler/simplified-operator.h
- src/compiler/typer.cc
- src/compiler/verifier.cc
- src/runtime/runtime-debug.cc
- src/runtime/runtime.h
WIP for https://linear.app/replay/issue/RUN-691
> Optimize updating progress counter

- src/debug/debug.cc
- src/inspector/v8-debugger.cc
For https://linear.app/replay/issue/RUN-735
> Support disallowing events when running new script handlers

- src/compiler/bytecode-graph-builder.cc
https://linear.app/replay/issue/RUN-740
> Only optimize progress counter updates when recording

- src/api/api.cc
- src/execution/isolate.cc
- src/execution/isolate.h
https://linear.app/replay/issue/RUN-741
> Only invoke API interrupts at progress updates while recording

- src/api/api.cc
Adds `V8RecordReplayOnAnnotation` to facade `RecordReplayOnAnnotation` from the driver
> Expose onAnnotation

- src/compiler/bytecode-graph-builder.cc
https://linear.app/replay/issue/RUN-745
> Disable optimized progress counter updates

- src/api/api.cc
- src/baseline/baseline-compiler.cc
- src/compiler/bytecode-graph-builder.cc
- src/runtime/runtime-debug.cc
https://linear.app/replay/issue/RUN-764
> Add env var to assert on JS progress changes

- src/api/api.cc
For https://linear.app/replay/issue/RUN-749
> Add feature for initializing window proxies

- src/heap/local-heap.cc
https://linear.app/replay/issue/RUN-759
> Disallow events when triggering collection from script streaming task

- src/compiler/bytecode-graph-builder.cc
https://linear.app/replay/issue/RUN-775
> Re-disable optimized progress counter updates

- src/api/api.cc
- src/execution/isolate.cc
- src/execution/isolate.h
https://linear.app/replay/issue/RUN-786
> Support recording/replaying API interrupts

- src/api/api.cc
https://linear.app/replay/issue/RUN-798
> Add feature for react devtools backend hook

- src/inspector/injected-script.cc
https://linear.app/replay/issue/RUN-815
> Only set remote object persistent ID on main thread

- src/heap/heap.cc
https://linear.app/replay/issue/RUN-962
> Disallow events when handling memory pressure notifications

- src/heap/paged-spaces.cc
https://linear.app/replay/issue/RUN-1088
> Avoid interacting with recording when refilling paged spaces

- src/api/api.cc
For https://linear.app/replay/issue/RUN-571
> Add new recording/replaying feature

- src/api/api.cc
* Part of https://linear.app/replay/issue/RUN-1061/chromium-render-eventslist
> add `RecordReplayOnEvent`

- src/execution/execution.cc
https://linear.app/replay/issue/RUN-1092
> Ignore script execution callback when running record/replay scripts

- src/api/api.cc
https://linear.app/replay/issue/RUN-1110
> Watch for exception unwinds with no pending exception

- include/v8.h
- src/api/api.cc
- src/execution/execution.cc
- src/inspector/injected-script.cc
- src/inspector/value-mirror.cc
- src/runtime/runtime-debug.cc
For https://linear.app/replay/issue/RUN-999
> Add method for AreEventsPassedThrough, minor cleanup

- src/heap/concurrent-allocator.cc
https://linear.app/replay/issue/RUN-1115
> Disallow events when doing concurrent heap allocation

- src/heap/heap.cc
https://linear.app/replay/issue/RUN-1149
> Avoid interacting with recording while waiting for sweeping to complete

- src/heap/heap.cc
https://linear.app/replay/issue/RUN-1149
> Disallow events while waiting for sweeping to complete

- src/api/api.cc
- src/debug/debug.cc
https://linear.app/replay/issue/RUN-1194
> Implement GetPossibleBreakpoints callback

- src/api/api.cc
For https://linear.app/replay/issue/RUN-1182
> Add feature for places where weak pointers are avoided

- src/execution/isolate.cc
… crash.
https://linear.app/replay/issue/RUN-1258/[superblocks]-had-18-recording-crashes-in-the-past-week
> RUN-1258: hackfix: pending_exception disappears sometimes, but we don't want to

- src/inspector/value-mirror.cc
* [Explanations](https://linear.app/replay/issue/RUN-1315#comment-b24c99cc)
* https://linear.app/replay/issue/RUN-1407/improve-getobjectpreview-performance-part-1
> RUN-1407: improve getObjectPreview performance

- src/api/api.cc
- src/base/cpu.cc
- src/base/logging.cc
- src/base/platform/mutex.cc
- src/execution/isolate.cc
- src/execution/isolate.h
- src/heap/local-heap.cc
- src/logging/metrics.h
- src/runtime/runtime-debug.cc
- src/trap-handler/handler-shared.cc
https://linear.app/replay/issue/RUN-1452
> Support building on windows

- include/v8.h
- src/api/api.cc
https://linear.app/replay/issue/RUN-1480
> Add binding for RecordReplayAllowSideEffects

- src/inspector/value-mirror.cc
- src/objects/keys.cc
* Fixes 2 more crashes: https://linear.app/replay/issue/RUN-1315#comment-26f96699
* [Test](https://github.com/replayio/build-test-dashboard/blob/master/a5620cb7-3732-4285-9d5d-2666b8416bc0) results: 10/150 failed
* [Crash results](https://ui.honeycomb.io/replay/datasets/backend/result/kHzDCmwYAvy):
* 2 fatals
* 0 commands
> RUN-1429: fixing two crash-inducing bugs

- src/debug/debug.cc
We already crash if other errors percolate from the command invocation, so just do the same if we are passed an exception object.  This also opens the door to do proper error reporting from commands.
> Crash if we see command errors.

- src/execution/microtask-queue.h
* This is not seemingly helpful quite yet. I saw it in a few places where I thought it might be helpful, but I cannot remember where and I don't want to leave this in on a hunch.
> Remove unnecessary Assert

- src/api/api.cc
Paired w/ https://github.com/replayio/chromium/pull/535
> RUN-1537: rename feature: task-lifetime

- src/api/api.cc
https://linear.app/replay/issue/RUN-1683
WIP
> Add feature

- src/debug/debug.cc
- src/runtime/runtime-debug.cc
https://linear.app/replay/issue/RUN-1702
> Look for persistent IDs in all persistent ID weak maps

- src/objects/js-objects.cc
* paired w/ https://github.com/replayio/chromium/pull/609
* https://linear.app/replay/issue/RUN-1675#comment-d2d05d71
> Assert JSDate::CurrentTimeValue

- src/api/api.cc
- src/debug/debug.cc
- src/execution/execution.cc
- src/execution/microtask-queue.h
- src/runtime/runtime-debug.cc
* Paired w/ https://github.com/replayio/chromium/pull/645
* https://linear.app/replay/issue/RUN-1692#comment-78f4ae05
> RUN-1692: More Work on JS Divergences

- src/base/platform/platform-darwin.cc
- src/heap/local-heap.cc
https://linear.app/replay/issue/RUN-1857
WIP
> Assorted fixes for macOS/ARM

- src/heap/local-heap.cc
https://linear.app/replay/issue/RUN-1891
WIP
> Assorted fixes for windows

- include/v8.h
- src/api/api.cc
- src/heap/gc-tracer.cc
- src/heap/heap.cc
- src/heap/memory-reducer.cc
- src/objects/value-serializer.cc
- src/profiler/heap-snapshot-generator.cc
- src/wasm/wasm-code-manager.h
V8 side of https://linear.app/replay/issue/RUN-2070
WIP
> Use recorder feature API

- src/api/api.cc
- src/runtime/runtime-debug.cc
https://linear.app/replay/issue/RUN-2072
> Use recorder assert data APIs for keeping track of JS progress

- include/v8.h
- src/api/api.cc
For https://linear.app/replay/issue/RUN-2100
> Add API for whether any features are disabled

- src/inspector/v8-inspector-impl.cc
* fix build errors (following https://github.com/replayio/chromium-v8/pull/155)
* https://linear.app/replay/issue/RUN-2042#comment-7e676024
> RUN-2109: Improve ExecutionContext lifetime diagnostics - Part 2

- src/api/api.cc
For https://linear.app/replay/issue/RUN-2065
> Add features for changes to default flag values

- src/heap/heap.cc
https://linear.app/replay/issue/RUN-2176
> Disallow events while notifying memory reducer

- src/api/api.cc
https://linear.app/replay/issue/RUN-2210
> Clean up symbol loading

- src/api/api.cc
- src/codegen/compilation-cache.cc
- src/codegen/compiler.cc
- src/debug/debug.cc
- src/parsing/parse-info.cc
- src/parsing/parse-info.h
https://linear.app/replay/issue/RUN-2130
WIP
> Use compilation cache when recording

- src/codegen/compiler.cc
- src/debug/debug.cc
https://linear.app/replay/issue/RUN-2236
> Ignore compilation cache hits on unknown scripts

- src/api/api.cc
https://linear.app/replay/issue/RUN-2288
> Only update gRecordReplayCheckProgress on the main thread

- include/v8.h
- src/api/api.cc
- src/execution/isolate.cc
- src/execution/microtask-queue.h
https://linear.app/replay/issue/RUN-2295
> Optimizations for AreEventsDisallowed()

- src/execution/futex-emulation.cc
For #RUN-2418 (https://linear.app/replay/issue/RUN-2418/add-asserts-to-futexemulationwaitsync)
Under RUN-2378.
> Asserts in FutexEmulation::WaitSync.

- src/execution/futex-emulation.cc
- src/execution/futex-emulation.h
Backs out https://github.com/replayio/chromium-v8/pull/176
> Backout 9da77f12953e5b4d228a1c6496845c237cbcda3f.

- src/inspector/injected-script.cc
- src/inspector/v8-inspector-session-impl.cc
- src/inspector/v8-runtime-agent-impl.cc
* paired w/ https://github.com/replayio/chromium/pull/861
* https://linear.app/replay/issue/RUN-2486#comment-8e7778cb
* [Tests](https://buildkite.com/replay/testing-runtime-e2e/builds/1280#018a08e9-f219-4974-b1b1-cb731538c8c2) look good ✔
> More diagnostics for "Cannot find context with specified id"

- include/v8.h
- src/api/api.cc
- src/inspector/v8-inspector-impl.cc
* paired w/ https://github.com/replayio/chromium/pull/869
* https://linear.app/replay/issue/RUN-2486#comment-738515ae
* Tests pass (despite timeout issues) ✅
> Diagnostics in V8InspectorImpl::getContext

- include/v8.h
- src/api/api.cc
- src/inspector/v8-inspector-session-impl.cc
* Paired w/ https://github.com/replayio/chromium/pull/898
* https://linear.app/replay/issue/RUN-2486/react-devtools-breaks-because-we-cannot-evaluate-code-at-some-points#comment-5e65dada
> Trace `V8InspectorSessionImpl` ctor

- include/v8.h
- src/api/api.cc
- src/debug/debug.cc
- src/execution/execution.cc
- src/runtime/runtime-debug.cc
> Report performance events when advancing execution progress counter

- include/v8.h
- src/api/api.cc
- src/debug/debug.cc
- src/execution/execution.cc
- src/runtime/runtime-debug.cc
This reverts commit 7adbeb591efc10f023d5010c2662028cfce0d7bb.
> Revert "Report performance events when advancing execution progress counter (#200)"

- include/v8.h
- src/api/api.cc
- src/objects/value-serializer.cc
* paired w/ https://github.com/replayio/chromium/pull/1025
* https://linear.app/replay/issue/RUN-3015/add-autoassertbufferallocations-to-v8
> [RUN-3015] add AutoAssertBufferAllocations

- include/v8.h
- src/api/api.cc
* paired w/ 
* https://linear.app/replay/issue/RUN-864/isolate-greplayscript#comment-02497924
> [RUN-864] Fix and rename ReadReplayFileContents

- src/inspector/v8-inspector-session-impl.cc
- src/inspector/v8-inspector-session-impl.h
- src/inspector/v8-runtime-agent-impl.cc
https://linear.app/replay/issue/RUN-3238/annotate-cdp-message-dispatches-and-results
WIP
> Annotate CDP message dispatches and results

- src/inspector/v8-runtime-agent-impl.cc
https://linear.app/replay/issue/RUN-3244/mismatch-in-recordreplaymessageannotation
> Disallow events in more places when runtime agent sends CDP events

- include/v8.h
- src/api/api.cc
> Add support for tracking dependencies using recorder API

- src/api/api.cc
- src/execution/execution.cc
> Assorted fixes for dependency graph

- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1174
* https://linear.app/replay/issue/TT-820/fix-applicationdatamismatch-generated-by-getprogressmismatchmessage
> [TT-820] Fix GetProgressMismatchMessage

- include/replayio.h
- include/v8.h
- src/api/api.cc
- src/base/platform/condition-variable.cc
- src/base/platform/elapsed-timer.h
- src/base/replayio.h
- src/codegen/compiler.cc
- src/codegen/x64/assembler-x64.cc
- src/compiler/backend/code-generator.cc
- src/debug/debug.cc
- src/execution/futex-emulation.cc
- src/execution/isolate.cc
- src/heap/allocation-observer.cc
- src/heap/concurrent-allocator.cc
- src/heap/concurrent-marking.cc
- src/heap/cppgc/stats-collector.cc
- src/heap/cppgc/sweeper.cc
- src/heap/heap.cc
- src/heap/incremental-marking-job.cc
- src/heap/incremental-marking.cc
- src/heap/local-heap.cc
- src/heap/paged-spaces.cc
- src/inspector/v8-inspector-session-impl.cc
- src/inspector/v8-runtime-agent-impl.cc
- src/logging/counters-scopes.h
- src/logging/metrics.h
- src/objects/objects.cc
- src/runtime/runtime-promise.cc
- src/utils/utils-inl.h
- src/wasm/module-compiler.cc
* paired w/ https://github.com/replayio/chromium/pull/1173/files
* https://linear.app/replay/issue/TT-187/[superblocks]-mismatch-involving-promisereject#comment-adb32358
> [TT-819] Fix Asserts in RejectPromise

- src/api/api.cc
- src/objects/objects.cc
https://linear.app/replay/issue/TT-800/enable-dependency-graph-by-default
> Enable dependency graph by default

- src/baseline/baseline-compiler.cc
- src/compiler/bytecode-graph-builder.cc
- src/debug/debug.cc
- src/interpreter/bytecode-array-builder.cc
- src/interpreter/bytecode-array-builder.h
- src/interpreter/bytecode-generator.cc
- src/interpreter/bytecodes.h
- src/interpreter/interpreter-generator.cc
- src/maglev/maglev-graph-builder.cc
- src/runtime/runtime-debug.cc
- src/runtime/runtime.h
https://linear.app/replay/issue/TT-969/allow-accessing-return-value-when-paused-at-exit-site
> Allow accessing return value when paused at exit site

- src/api/api.cc
- src/execution/isolate.cc
- src/objects/objects.cc
- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1202
* https://linear.app/replay/issue/TT-1029/mismatch-in-agentgroupschedulerimplperformmicrotaskcheckpoint#comment-69337713
> [TT-1030] More Asserts for `JSPromise::set_has_handler`

- src/api/api.cc
- src/debug/debug.cc
- src/execution/execution.cc
- src/interpreter/bytecode-array-builder.cc
- src/interpreter/bytecode-generator.cc
- src/runtime/runtime-debug.cc
> Assorted fixes

- src/api/api.cc
- src/codegen/compiler.cc
- src/compiler/simplified-operator.cc
- src/interpreter/bytecode-array-builder.cc
- src/interpreter/bytecode-array-builder.h
- src/interpreter/bytecode-generator.cc
- src/objects/js-objects.cc
- src/parsing/parse-info.cc
- src/parsing/parse-info.h
- src/runtime/runtime-debug.cc
WIP for https://linear.app/replay/issue/TT-1106/
> Assorted diagnostic improvements

- src/objects/value-serializer.cc
* paired w/ https://github.com/replayio/chromium/pull/1241
> Assert ValueSerializer::WriteJSArray

- include/replayio-macros.h
- include/v8.h
- src/api/api.cc
- src/objects/value-serializer.cc
- src/runtime/runtime-debug.cc
* paired w/ https://github.com/replayio/chromium/pull/1247
* https://linear.app/replay/issue/TT-492/[vercel]-mismatch-in-valuedeserializer-and-valueserializer#comment-75d5ecc6
> Assert more of ValueSerializer::WriteValue

- src/api/api.cc
- src/execution/messages.cc
- src/objects/objects.cc
* paired w/ https://github.com/replayio/chromium/pull/1256
* https://linear.app/replay/issue/TT-341/[zillow]-js-blocked-a-frame-with-origin-part-2#comment-91fe000b
> [TT-341] Suppress scheduled exceptions when handling commands

- include/replayio-macros.h
- src/objects/value-serializer.cc
* https://linear.app/replay/issue/TT-1415/disable-tt-492-asserts
* * https://github.com/replayio/chromium/pull/1270
> Disable TT-492 Asserts

- src/api/api.cc
- src/codegen/compiler.cc
- src/compiler/js-call-reducer.cc
- src/compiler/js-native-context-specialization.cc
- src/debug/debug.cc
- src/execution/isolate.cc
- src/ic/ic.cc
- src/runtime/runtime-debug.cc
- src/runtime/runtime-promise.cc
https://linear.app/replay/issue/TT-1440/support-asserting-on-dependency-graph-contents
> Support asserting on dependency graph contents

- src/debug/debug.cc
* https://linear.app/replay/issue/PRO-896/expose-promise-persistentid-in-dg
* paired w/ https://github.com/replayio/chromium/pull/1310
* Tests: https://buildkite.com/replay/runtime-build-and-test/builds/513
> [PRO-896] Expose promise persistentId in DG

- src/debug/debug.cc
- src/objects/objects.cc
I don't expect this to be fully correct, I don't even know if this code compiles. It is just a somewhat concrete proposal for what kind of changes would fit the current dependency graph design (in my opinion, of course).
> Refactor proposal with adoption edges

- src/ast/ast.h
- src/interpreter/bytecode-array-builder.cc
- src/interpreter/bytecode-array-builder.h
- src/interpreter/bytecode-generator.cc
- src/parsing/parser-base.h
- src/parsing/parser.cc
- src/parsing/parser.h
- src/parsing/preparser.h
* https://linear.app/replay/issue/PRO-1092/fix-post-argument-call-expression-breakpoints
* paired w/ https://github.com/replayio/chromium/pull/1318
> [PRO-1092] Fix call expression breakpoints

- include/v8.h
- src/api/api.cc
- src/execution/messages.cc
* paired w/ https://github.com/replayio/chromium/pull/1321
* https://linear.app/replay/issue/PRO-1150/analysis-fatal-errors-causing-many-chats-to-fail#comment-010efc16
> [PRO-1150] Replay error messages in `MessageFormatter::Format`
